apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-cluster-configmap
data:
  redis.conf: |
    port 6379
    bind 0.0.0.0
    protected-mode no

    cluster-enabled yes
    cluster-config-file nodes.conf
    cluster-node-timeout 5000

    cluster-announce-hostname ${HOSTNAME}.redis-cluster-service
    cluster-announce-port 6379
    cluster-announce-bus-port 16379

    appendonly yes
    dir /data
